# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.cache/wt [current_project]
set_property parent.project_path C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/version1_stream_interconnect_0.xci
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_1/bd_8ee2_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_1/bd_8ee2_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_2/bd_8ee2_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_3/bd_8ee2_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_4/bd_8ee2_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_5/bd_8ee2_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_6/bd_8ee2_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_10/bd_8ee2_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_11/bd_8ee2_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_12/bd_8ee2_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_16/bd_8ee2_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_17/bd_8ee2_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_18/bd_8ee2_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_22/bd_8ee2_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_23/bd_8ee2_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_24/bd_8ee2_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_28/bd_8ee2_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_29/bd_8ee2_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_30/bd_8ee2_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_31/bd_8ee2_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_35/bd_8ee2_s04a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_36/bd_8ee2_sarn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_37/bd_8ee2_srn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_41/bd_8ee2_s05a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_42/bd_8ee2_sarn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_43/bd_8ee2_srn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_47/bd_8ee2_s06a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_48/bd_8ee2_sarn_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_49/bd_8ee2_srn_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_53/bd_8ee2_s07a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_54/bd_8ee2_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_55/bd_8ee2_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_56/bd_8ee2_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_60/bd_8ee2_s08a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_61/bd_8ee2_sarn_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_62/bd_8ee2_srn_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_66/bd_8ee2_s09a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_67/bd_8ee2_sarn_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_68/bd_8ee2_srn_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_72/bd_8ee2_s10a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_73/bd_8ee2_sarn_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_74/bd_8ee2_srn_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_78/bd_8ee2_s11a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_79/bd_8ee2_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_80/bd_8ee2_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_81/bd_8ee2_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_85/bd_8ee2_s12a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_86/bd_8ee2_sarn_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_87/bd_8ee2_srn_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_91/bd_8ee2_s13a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_92/bd_8ee2_sarn_10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_93/bd_8ee2_srn_10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_97/bd_8ee2_s14a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_98/bd_8ee2_sarn_11_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_99/bd_8ee2_srn_11_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_103/bd_8ee2_s15a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_104/bd_8ee2_sawn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_105/bd_8ee2_swn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_106/bd_8ee2_sbn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_107/bd_8ee2_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_108/bd_8ee2_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_109/bd_8ee2_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_110/bd_8ee2_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_111/bd_8ee2_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/bd_0/ip/ip_112/bd_8ee2_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

set cached_ip [config_ip_cache -export -no_bom  -dir C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.runs/version1_stream_interconnect_0_synth_1 -new_name version1_stream_interconnect_0 -ip [get_ips version1_stream_interconnect_0]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top version1_stream_interconnect_0 -part xc7z020clg400-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix version1_stream_interconnect_0_ version1_stream_interconnect_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ version1_stream_interconnect_0_stub.v
 lappend ipCachedFiles version1_stream_interconnect_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ version1_stream_interconnect_0_stub.vhdl
 lappend ipCachedFiles version1_stream_interconnect_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ version1_stream_interconnect_0_sim_netlist.v
 lappend ipCachedFiles version1_stream_interconnect_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ version1_stream_interconnect_0_sim_netlist.vhdl
 lappend ipCachedFiles version1_stream_interconnect_0_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp version1_stream_interconnect_0.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips version1_stream_interconnect_0]
}

rename_ref -prefix_all version1_stream_interconnect_0_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef version1_stream_interconnect_0.dcp
create_report "version1_stream_interconnect_0_synth_1_synth_report_utilization_0" "report_utilization -file version1_stream_interconnect_0_utilization_synth.rpt -pb version1_stream_interconnect_0_utilization_synth.pb"

if { [catch {
  file copy -force C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.runs/version1_stream_interconnect_0_synth_1/version1_stream_interconnect_0.dcp c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/version1_stream_interconnect_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/version1_stream_interconnect_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/version1_stream_interconnect_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/version1_stream_interconnect_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/version1_stream_interconnect_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.runs/version1_stream_interconnect_0_synth_1/version1_stream_interconnect_0.dcp c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/version1_stream_interconnect_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.runs/version1_stream_interconnect_0_synth_1/version1_stream_interconnect_0_stub.v c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/version1_stream_interconnect_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.runs/version1_stream_interconnect_0_synth_1/version1_stream_interconnect_0_stub.vhdl c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/version1_stream_interconnect_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.runs/version1_stream_interconnect_0_synth_1/version1_stream_interconnect_0_sim_netlist.v c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/version1_stream_interconnect_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.runs/version1_stream_interconnect_0_synth_1/version1_stream_interconnect_0_sim_netlist.vhdl c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/version1_stream_interconnect_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.ip_user_files/ip/version1_stream_interconnect_0]} {
  catch { 
    file copy -force c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/version1_stream_interconnect_0_stub.v C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.ip_user_files/ip/version1_stream_interconnect_0
  }
}

if {[file isdir C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.ip_user_files/ip/version1_stream_interconnect_0]} {
  catch { 
    file copy -force c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_0/version1_stream_interconnect_0_stub.vhdl C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.ip_user_files/ip/version1_stream_interconnect_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
