# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_xbar_0/version3_xbar_0.xci
# IP: The module: 'version3_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_xbar_0/version3_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'version3_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_xbar_0/version3_xbar_0.xci
# IP: The module: 'version3_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_xbar_0/version3_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'version3_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
