# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/version1_stream_interconnect_1.xci
# IP: The module: 'version1_stream_interconnect_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/bd_4e23.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_0/bd_4e23_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_1/bd_4e23_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_2/bd_4e23_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_3/bd_4e23_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_4/bd_4e23_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_5/bd_4e23_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_6/bd_4e23_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_7/bd_4e23_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_8/bd_4e23_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_9/bd_4e23_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_10/bd_4e23_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_11/bd_4e23_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_12/bd_4e23_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_13/bd_4e23_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_14/bd_4e23_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_15/bd_4e23_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_16/bd_4e23_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_17/bd_4e23_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_18/bd_4e23_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_19/bd_4e23_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_20/bd_4e23_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_21/bd_4e23_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_22/bd_4e23_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_23/bd_4e23_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_24/bd_4e23_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_25/bd_4e23_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_26/bd_4e23_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_27/bd_4e23_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_28/bd_4e23_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_29/bd_4e23_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_30/bd_4e23_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_31/bd_4e23_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_32/bd_4e23_s04mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_33/bd_4e23_s04tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_34/bd_4e23_s04sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_35/bd_4e23_s04a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_36/bd_4e23_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_37/bd_4e23_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_38/bd_4e23_s05mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_39/bd_4e23_s05tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_40/bd_4e23_s05sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_41/bd_4e23_s05a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_42/bd_4e23_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_43/bd_4e23_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_44/bd_4e23_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_45/bd_4e23_s06mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_46/bd_4e23_s06tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_47/bd_4e23_s06sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_48/bd_4e23_s06a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_49/bd_4e23_sarn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_50/bd_4e23_srn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_51/bd_4e23_s07mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_52/bd_4e23_s07tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_53/bd_4e23_s07sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_54/bd_4e23_s07a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_55/bd_4e23_sarn_5.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_56/bd_4e23_srn_5.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_57/bd_4e23_s08mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_58/bd_4e23_s08tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_59/bd_4e23_s08sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_60/bd_4e23_s08a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_61/bd_4e23_sawn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_62/bd_4e23_swn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_63/bd_4e23_sbn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_64/bd_4e23_s09mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_65/bd_4e23_s09tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_66/bd_4e23_s09sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_67/bd_4e23_s09a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_68/bd_4e23_sarn_6.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_69/bd_4e23_srn_6.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_70/bd_4e23_s10mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_71/bd_4e23_s10tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_72/bd_4e23_s10sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_73/bd_4e23_s10a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_74/bd_4e23_sarn_7.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_75/bd_4e23_srn_7.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_76/bd_4e23_s11mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_77/bd_4e23_s11tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_78/bd_4e23_s11sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_79/bd_4e23_s11a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_80/bd_4e23_sawn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_81/bd_4e23_swn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_82/bd_4e23_sbn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_83/bd_4e23_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_84/bd_4e23_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_85/bd_4e23_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_86/bd_4e23_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_87/bd_4e23_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_88/bd_4e23_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_89/bd_4e23_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'version1_stream_interconnect_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_1/bd_4e23_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_1/bd_4e23_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_2/bd_4e23_arsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_3/bd_4e23_rsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_4/bd_4e23_awsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_5/bd_4e23_wsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_6/bd_4e23_bsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_10/bd_4e23_s00a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_11/bd_4e23_sarn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_12/bd_4e23_srn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_16/bd_4e23_s01a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_17/bd_4e23_sarn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_18/bd_4e23_srn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_22/bd_4e23_s02a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_23/bd_4e23_sawn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_24/bd_4e23_swn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_25/bd_4e23_sbn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_29/bd_4e23_s03a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_30/bd_4e23_sarn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_31/bd_4e23_srn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_35/bd_4e23_s04a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_36/bd_4e23_sarn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_37/bd_4e23_srn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_41/bd_4e23_s05a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_42/bd_4e23_sawn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_43/bd_4e23_swn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_44/bd_4e23_sbn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_48/bd_4e23_s06a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_49/bd_4e23_sarn_4_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_50/bd_4e23_srn_4_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_54/bd_4e23_s07a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_55/bd_4e23_sarn_5_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_56/bd_4e23_srn_5_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_60/bd_4e23_s08a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_61/bd_4e23_sawn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_62/bd_4e23_swn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_63/bd_4e23_sbn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_67/bd_4e23_s09a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_68/bd_4e23_sarn_6_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_69/bd_4e23_srn_6_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_73/bd_4e23_s10a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_74/bd_4e23_sarn_7_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_75/bd_4e23_srn_7_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_79/bd_4e23_s11a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_80/bd_4e23_sawn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_81/bd_4e23_swn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_82/bd_4e23_sbn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_83/bd_4e23_m00s2a_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_84/bd_4e23_m00arn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_85/bd_4e23_m00rn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_86/bd_4e23_m00awn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_87/bd_4e23_m00wn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_88/bd_4e23_m00bn_0_ooc.xdc

# IP: C:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/version1_stream_interconnect_1.xci
# IP: The module: 'version1_stream_interconnect_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/bd_4e23.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_0/bd_4e23_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_1/bd_4e23_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_2/bd_4e23_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_3/bd_4e23_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_4/bd_4e23_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_5/bd_4e23_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_6/bd_4e23_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_7/bd_4e23_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_8/bd_4e23_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_9/bd_4e23_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_10/bd_4e23_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_11/bd_4e23_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_12/bd_4e23_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_13/bd_4e23_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_14/bd_4e23_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_15/bd_4e23_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_16/bd_4e23_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_17/bd_4e23_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_18/bd_4e23_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_19/bd_4e23_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_20/bd_4e23_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_21/bd_4e23_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_22/bd_4e23_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_23/bd_4e23_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_24/bd_4e23_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_25/bd_4e23_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_26/bd_4e23_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_27/bd_4e23_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_28/bd_4e23_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_29/bd_4e23_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_30/bd_4e23_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_31/bd_4e23_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_32/bd_4e23_s04mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_33/bd_4e23_s04tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_34/bd_4e23_s04sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_35/bd_4e23_s04a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_36/bd_4e23_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_37/bd_4e23_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_38/bd_4e23_s05mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_39/bd_4e23_s05tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_40/bd_4e23_s05sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_41/bd_4e23_s05a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_42/bd_4e23_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_43/bd_4e23_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_44/bd_4e23_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_45/bd_4e23_s06mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_46/bd_4e23_s06tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_47/bd_4e23_s06sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_48/bd_4e23_s06a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_49/bd_4e23_sarn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_50/bd_4e23_srn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_51/bd_4e23_s07mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_52/bd_4e23_s07tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_53/bd_4e23_s07sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_54/bd_4e23_s07a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_55/bd_4e23_sarn_5.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_56/bd_4e23_srn_5.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_57/bd_4e23_s08mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_58/bd_4e23_s08tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_59/bd_4e23_s08sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_60/bd_4e23_s08a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_61/bd_4e23_sawn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_62/bd_4e23_swn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_63/bd_4e23_sbn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_64/bd_4e23_s09mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_65/bd_4e23_s09tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_66/bd_4e23_s09sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_67/bd_4e23_s09a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_68/bd_4e23_sarn_6.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_69/bd_4e23_srn_6.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_70/bd_4e23_s10mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_71/bd_4e23_s10tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_72/bd_4e23_s10sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_73/bd_4e23_s10a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_74/bd_4e23_sarn_7.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_75/bd_4e23_srn_7.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_76/bd_4e23_s11mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_77/bd_4e23_s11tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_78/bd_4e23_s11sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_79/bd_4e23_s11a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_80/bd_4e23_sawn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_81/bd_4e23_swn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_82/bd_4e23_sbn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_83/bd_4e23_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_84/bd_4e23_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_85/bd_4e23_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_86/bd_4e23_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_87/bd_4e23_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_88/bd_4e23_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_89/bd_4e23_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'version1_stream_interconnect_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_1/bd_4e23_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_1/bd_4e23_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_2/bd_4e23_arsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_3/bd_4e23_rsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_4/bd_4e23_awsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_5/bd_4e23_wsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_6/bd_4e23_bsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_10/bd_4e23_s00a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_11/bd_4e23_sarn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_12/bd_4e23_srn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_16/bd_4e23_s01a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_17/bd_4e23_sarn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_18/bd_4e23_srn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_22/bd_4e23_s02a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_23/bd_4e23_sawn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_24/bd_4e23_swn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_25/bd_4e23_sbn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_29/bd_4e23_s03a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_30/bd_4e23_sarn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_31/bd_4e23_srn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_35/bd_4e23_s04a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_36/bd_4e23_sarn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_37/bd_4e23_srn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_41/bd_4e23_s05a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_42/bd_4e23_sawn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_43/bd_4e23_swn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_44/bd_4e23_sbn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_48/bd_4e23_s06a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_49/bd_4e23_sarn_4_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_50/bd_4e23_srn_4_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_54/bd_4e23_s07a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_55/bd_4e23_sarn_5_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_56/bd_4e23_srn_5_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_60/bd_4e23_s08a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_61/bd_4e23_sawn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_62/bd_4e23_swn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_63/bd_4e23_sbn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_67/bd_4e23_s09a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_68/bd_4e23_sarn_6_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_69/bd_4e23_srn_6_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_73/bd_4e23_s10a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_74/bd_4e23_sarn_7_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_75/bd_4e23_srn_7_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_79/bd_4e23_s11a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_80/bd_4e23_sawn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_81/bd_4e23_swn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_82/bd_4e23_sbn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_83/bd_4e23_m00s2a_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_84/bd_4e23_m00arn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_85/bd_4e23_m00rn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_86/bd_4e23_m00awn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_87/bd_4e23_m00wn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_stream_interconnect_1/bd_0/ip/ip_88/bd_4e23_m00bn_0_ooc.xdc
