# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/version3/version3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3 || ORIG_REF_NAME==version3} -quiet] -quiet

# IP: bd/version3/ip/version3_axi_gpio_0_0/version3_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_axi_gpio_0_0 || ORIG_REF_NAME==version3_axi_gpio_0_0} -quiet] -quiet

# IP: bd/version3/ip/version3_processing_system7_0_0/version3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_processing_system7_0_0 || ORIG_REF_NAME==version3_processing_system7_0_0} -quiet] -quiet

# IP: bd/version3/ip/version3_rst_ps7_0_100M_0/version3_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_rst_ps7_0_100M_0 || ORIG_REF_NAME==version3_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/version3/ip/version3_stream_interconnect_fir_0/version3_stream_interconnect_fir_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_stream_interconnect_fir_0 || ORIG_REF_NAME==version3_stream_interconnect_fir_0} -quiet] -quiet

# IP: bd/version3/ip/version3_CONFIG_DMA_1/version3_CONFIG_DMA_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_CONFIG_DMA_1 || ORIG_REF_NAME==version3_CONFIG_DMA_1} -quiet] -quiet

# IP: bd/version3/ip/version3_DATA_DMA_1/version3_DATA_DMA_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_DATA_DMA_1 || ORIG_REF_NAME==version3_DATA_DMA_1} -quiet] -quiet

# IP: bd/version3/ip/version3_RELOAD_DMA_1/version3_RELOAD_DMA_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_RELOAD_DMA_1 || ORIG_REF_NAME==version3_RELOAD_DMA_1} -quiet] -quiet

# IP: bd/version3/ip/version3_fir_compiler_0_1/version3_fir_compiler_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_fir_compiler_0_1 || ORIG_REF_NAME==version3_fir_compiler_0_1} -quiet] -quiet

# IP: bd/version3/ip/version3_CONFIG_DMA_2/version3_CONFIG_DMA_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_CONFIG_DMA_2 || ORIG_REF_NAME==version3_CONFIG_DMA_2} -quiet] -quiet

# IP: bd/version3/ip/version3_DATA_DMA_2/version3_DATA_DMA_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_DATA_DMA_2 || ORIG_REF_NAME==version3_DATA_DMA_2} -quiet] -quiet

# IP: bd/version3/ip/version3_RELOAD_DMA_2/version3_RELOAD_DMA_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_RELOAD_DMA_2 || ORIG_REF_NAME==version3_RELOAD_DMA_2} -quiet] -quiet

# IP: bd/version3/ip/version3_fir_compiler_0_2/version3_fir_compiler_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_fir_compiler_0_2 || ORIG_REF_NAME==version3_fir_compiler_0_2} -quiet] -quiet

# IP: bd/version3/ip/version3_CONFIG_DMA_3/version3_CONFIG_DMA_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_CONFIG_DMA_3 || ORIG_REF_NAME==version3_CONFIG_DMA_3} -quiet] -quiet

# IP: bd/version3/ip/version3_DATA_DMA_3/version3_DATA_DMA_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_DATA_DMA_3 || ORIG_REF_NAME==version3_DATA_DMA_3} -quiet] -quiet

# IP: bd/version3/ip/version3_RELOAD_DMA_3/version3_RELOAD_DMA_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_RELOAD_DMA_3 || ORIG_REF_NAME==version3_RELOAD_DMA_3} -quiet] -quiet

# IP: bd/version3/ip/version3_fir_compiler_0_3/version3_fir_compiler_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_fir_compiler_0_3 || ORIG_REF_NAME==version3_fir_compiler_0_3} -quiet] -quiet

# IP: bd/version3/ip/version3_CONFIG_DMA_0/version3_CONFIG_DMA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_CONFIG_DMA_0 || ORIG_REF_NAME==version3_CONFIG_DMA_0} -quiet] -quiet

# IP: bd/version3/ip/version3_DATA_DMA_0/version3_DATA_DMA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_DATA_DMA_0 || ORIG_REF_NAME==version3_DATA_DMA_0} -quiet] -quiet

# IP: bd/version3/ip/version3_RELOAD_DMA_0/version3_RELOAD_DMA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_RELOAD_DMA_0 || ORIG_REF_NAME==version3_RELOAD_DMA_0} -quiet] -quiet

# IP: bd/version3/ip/version3_fir_compiler_0_0/version3_fir_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_fir_compiler_0_0 || ORIG_REF_NAME==version3_fir_compiler_0_0} -quiet] -quiet

# IP: bd/version3/ip/version3_xbar_1/version3_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_xbar_1 || ORIG_REF_NAME==version3_xbar_1} -quiet] -quiet

# IP: bd/version3/ip/version3_standard_interconnect_fir_0/version3_standard_interconnect_fir_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_standard_interconnect_fir_0 || ORIG_REF_NAME==version3_standard_interconnect_fir_0} -quiet] -quiet

# IP: bd/version3/ip/version3_stream_interconnect_fft_0/version3_stream_interconnect_fft_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_stream_interconnect_fft_0 || ORIG_REF_NAME==version3_stream_interconnect_fft_0} -quiet] -quiet

# IP: bd/version3/ip/version3_DMA_CONFIG_1/version3_DMA_CONFIG_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_DMA_CONFIG_1 || ORIG_REF_NAME==version3_DMA_CONFIG_1} -quiet] -quiet

# IP: bd/version3/ip/version3_DMA_DATA_1/version3_DMA_DATA_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_DMA_DATA_1 || ORIG_REF_NAME==version3_DMA_DATA_1} -quiet] -quiet

# IP: bd/version3/ip/version3_FFT_1/version3_FFT_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_FFT_1 || ORIG_REF_NAME==version3_FFT_1} -quiet] -quiet

# IP: bd/version3/ip/version3_axis_dwidth_converter_0_1/version3_axis_dwidth_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_axis_dwidth_converter_0_1 || ORIG_REF_NAME==version3_axis_dwidth_converter_0_1} -quiet] -quiet

# IP: bd/version3/ip/version3_DMA_CONFIG_2/version3_DMA_CONFIG_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_DMA_CONFIG_2 || ORIG_REF_NAME==version3_DMA_CONFIG_2} -quiet] -quiet

# IP: bd/version3/ip/version3_DMA_DATA_2/version3_DMA_DATA_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_DMA_DATA_2 || ORIG_REF_NAME==version3_DMA_DATA_2} -quiet] -quiet

# IP: bd/version3/ip/version3_FFT_2/version3_FFT_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_FFT_2 || ORIG_REF_NAME==version3_FFT_2} -quiet] -quiet

# IP: bd/version3/ip/version3_axis_dwidth_converter_0_2/version3_axis_dwidth_converter_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_axis_dwidth_converter_0_2 || ORIG_REF_NAME==version3_axis_dwidth_converter_0_2} -quiet] -quiet

# IP: bd/version3/ip/version3_xbar_0/version3_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_xbar_0 || ORIG_REF_NAME==version3_xbar_0} -quiet] -quiet

# IP: bd/version3/ip/version3_standard_interconnect_fft_0/version3_standard_interconnect_fft_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_standard_interconnect_fft_0 || ORIG_REF_NAME==version3_standard_interconnect_fft_0} -quiet] -quiet

# IP: bd/version3/ip/version3_DMA_CONFIG_3/version3_DMA_CONFIG_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_DMA_CONFIG_3 || ORIG_REF_NAME==version3_DMA_CONFIG_3} -quiet] -quiet

# IP: bd/version3/ip/version3_DMA_DATA_3/version3_DMA_DATA_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_DMA_DATA_3 || ORIG_REF_NAME==version3_DMA_DATA_3} -quiet] -quiet

# IP: bd/version3/ip/version3_FFT_3/version3_FFT_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_FFT_3 || ORIG_REF_NAME==version3_FFT_3} -quiet] -quiet

# IP: bd/version3/ip/version3_axis_dwidth_converter_0_3/version3_axis_dwidth_converter_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_axis_dwidth_converter_0_3 || ORIG_REF_NAME==version3_axis_dwidth_converter_0_3} -quiet] -quiet

# IP: bd/version3/ip/version3_DMA_CONFIG_0/version3_DMA_CONFIG_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_DMA_CONFIG_0 || ORIG_REF_NAME==version3_DMA_CONFIG_0} -quiet] -quiet

# IP: bd/version3/ip/version3_DMA_DATA_0/version3_DMA_DATA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_DMA_DATA_0 || ORIG_REF_NAME==version3_DMA_DATA_0} -quiet] -quiet

# IP: bd/version3/ip/version3_FFT_0/version3_FFT_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_FFT_0 || ORIG_REF_NAME==version3_FFT_0} -quiet] -quiet

# IP: bd/version3/ip/version3_axis_dwidth_converter_0_0/version3_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_axis_dwidth_converter_0_0 || ORIG_REF_NAME==version3_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/version3/ip/version3_auto_pc_0/version3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_auto_pc_0 || ORIG_REF_NAME==version3_auto_pc_0} -quiet] -quiet

# IP: bd/version3/ip/version3_xbar_2/version3_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_xbar_2 || ORIG_REF_NAME==version3_xbar_2} -quiet] -quiet

# IP: bd/version3/ip/version3_auto_pc_1/version3_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_auto_pc_1 || ORIG_REF_NAME==version3_auto_pc_1} -quiet] -quiet

# IP: bd/version3/ip/version3_axi_interconnect_0_0/version3_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version3_axi_interconnect_0_0 || ORIG_REF_NAME==version3_axi_interconnect_0_0} -quiet] -quiet

# XDC: bd/version3/version3_ooc.xdc
