-- (c) Copyright 1995-2020 Xilinx, Inc. All rights reserved.
-- 
-- This file contains confidential and proprietary information
-- of Xilinx, Inc. and is protected under U.S. and
-- international copyright and other intellectual property
-- laws.
-- 
-- DISCLAIMER
-- This disclaimer is not a license and does not grant any
-- rights to the materials distributed herewith. Except as
-- otherwise provided in a valid license issued to you by
-- Xilinx, and to the maximum extent permitted by applicable
-- law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
-- WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
-- AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
-- BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
-- INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
-- (2) Xilinx shall not be liable (whether in contract or tort,
-- including negligence, or under any other theory of
-- liability) for any loss or damage of any kind or nature
-- related to, arising under or in connection with these
-- materials, including for any direct, or any indirect,
-- special, incidental, or consequential loss or damage
-- (including loss of data, profits, goodwill, or any type of
-- loss or damage suffered as a result of any action brought
-- by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the
-- possibility of the same.
-- 
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-
-- safe, or for use in any application requiring fail-safe
-- performance, such as life-support or safety devices or
-- systems, Class III medical devices, nuclear facilities,
-- applications related to the deployment of airbags, or any
-- other applications that could lead to death, personal
-- injury, or severe property or environmental damage
-- (individually and collectively, "Critical
-- Applications"). Customer assumes the sole risk and
-- liability of any use of Xilinx products in Critical
-- Applications, subject only to applicable laws and
-- regulations governing limitations on product liability.
-- 
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
-- PART OF THIS FILE AT ALL TIMES.
-- 
-- DO NOT MODIFY THIS FILE.

-- IP VLNV: xilinx.com:ip:smartconnect:1.0
-- IP Revision: 11

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

ENTITY version1_stream_interconnect_0 IS
  PORT (
    aclk : IN STD_LOGIC;
    aresetn : IN STD_LOGIC;
    S00_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S00_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S00_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S00_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S00_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S00_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S00_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S00_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S00_AXI_arvalid : IN STD_LOGIC;
    S00_AXI_arready : OUT STD_LOGIC;
    S00_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S00_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S00_AXI_rlast : OUT STD_LOGIC;
    S00_AXI_rvalid : OUT STD_LOGIC;
    S00_AXI_rready : IN STD_LOGIC;
    S01_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S01_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S01_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S01_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S01_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S01_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S01_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S01_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S01_AXI_arvalid : IN STD_LOGIC;
    S01_AXI_arready : OUT STD_LOGIC;
    S01_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S01_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S01_AXI_rlast : OUT STD_LOGIC;
    S01_AXI_rvalid : OUT STD_LOGIC;
    S01_AXI_rready : IN STD_LOGIC;
    S02_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S02_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S02_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S02_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S02_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S02_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S02_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S02_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S02_AXI_arvalid : IN STD_LOGIC;
    S02_AXI_arready : OUT STD_LOGIC;
    S02_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S02_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S02_AXI_rlast : OUT STD_LOGIC;
    S02_AXI_rvalid : OUT STD_LOGIC;
    S02_AXI_rready : IN STD_LOGIC;
    S03_AXI_awaddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S03_AXI_awlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S03_AXI_awsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S03_AXI_awburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S03_AXI_awlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S03_AXI_awcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S03_AXI_awprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S03_AXI_awqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S03_AXI_awvalid : IN STD_LOGIC;
    S03_AXI_awready : OUT STD_LOGIC;
    S03_AXI_wdata : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S03_AXI_wstrb : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S03_AXI_wlast : IN STD_LOGIC;
    S03_AXI_wvalid : IN STD_LOGIC;
    S03_AXI_wready : OUT STD_LOGIC;
    S03_AXI_bresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S03_AXI_bvalid : OUT STD_LOGIC;
    S03_AXI_bready : IN STD_LOGIC;
    S04_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S04_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S04_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S04_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S04_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S04_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S04_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S04_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S04_AXI_arvalid : IN STD_LOGIC;
    S04_AXI_arready : OUT STD_LOGIC;
    S04_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S04_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S04_AXI_rlast : OUT STD_LOGIC;
    S04_AXI_rvalid : OUT STD_LOGIC;
    S04_AXI_rready : IN STD_LOGIC;
    S05_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S05_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S05_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S05_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S05_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S05_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S05_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S05_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S05_AXI_arvalid : IN STD_LOGIC;
    S05_AXI_arready : OUT STD_LOGIC;
    S05_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S05_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S05_AXI_rlast : OUT STD_LOGIC;
    S05_AXI_rvalid : OUT STD_LOGIC;
    S05_AXI_rready : IN STD_LOGIC;
    S06_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S06_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S06_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S06_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S06_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S06_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S06_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S06_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S06_AXI_arvalid : IN STD_LOGIC;
    S06_AXI_arready : OUT STD_LOGIC;
    S06_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S06_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S06_AXI_rlast : OUT STD_LOGIC;
    S06_AXI_rvalid : OUT STD_LOGIC;
    S06_AXI_rready : IN STD_LOGIC;
    S07_AXI_awaddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S07_AXI_awlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S07_AXI_awsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S07_AXI_awburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S07_AXI_awlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S07_AXI_awcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S07_AXI_awprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S07_AXI_awqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S07_AXI_awvalid : IN STD_LOGIC;
    S07_AXI_awready : OUT STD_LOGIC;
    S07_AXI_wdata : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S07_AXI_wstrb : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S07_AXI_wlast : IN STD_LOGIC;
    S07_AXI_wvalid : IN STD_LOGIC;
    S07_AXI_wready : OUT STD_LOGIC;
    S07_AXI_bresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S07_AXI_bvalid : OUT STD_LOGIC;
    S07_AXI_bready : IN STD_LOGIC;
    S08_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S08_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S08_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S08_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S08_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S08_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S08_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S08_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S08_AXI_arvalid : IN STD_LOGIC;
    S08_AXI_arready : OUT STD_LOGIC;
    S08_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S08_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S08_AXI_rlast : OUT STD_LOGIC;
    S08_AXI_rvalid : OUT STD_LOGIC;
    S08_AXI_rready : IN STD_LOGIC;
    S09_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S09_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S09_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S09_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S09_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S09_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S09_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S09_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S09_AXI_arvalid : IN STD_LOGIC;
    S09_AXI_arready : OUT STD_LOGIC;
    S09_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S09_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S09_AXI_rlast : OUT STD_LOGIC;
    S09_AXI_rvalid : OUT STD_LOGIC;
    S09_AXI_rready : IN STD_LOGIC;
    S10_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S10_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S10_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S10_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S10_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S10_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S10_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S10_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S10_AXI_arvalid : IN STD_LOGIC;
    S10_AXI_arready : OUT STD_LOGIC;
    S10_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S10_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S10_AXI_rlast : OUT STD_LOGIC;
    S10_AXI_rvalid : OUT STD_LOGIC;
    S10_AXI_rready : IN STD_LOGIC;
    S11_AXI_awaddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S11_AXI_awlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S11_AXI_awsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S11_AXI_awburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S11_AXI_awlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S11_AXI_awcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S11_AXI_awprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S11_AXI_awqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S11_AXI_awvalid : IN STD_LOGIC;
    S11_AXI_awready : OUT STD_LOGIC;
    S11_AXI_wdata : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S11_AXI_wstrb : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S11_AXI_wlast : IN STD_LOGIC;
    S11_AXI_wvalid : IN STD_LOGIC;
    S11_AXI_wready : OUT STD_LOGIC;
    S11_AXI_bresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S11_AXI_bvalid : OUT STD_LOGIC;
    S11_AXI_bready : IN STD_LOGIC;
    S12_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S12_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S12_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S12_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S12_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S12_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S12_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S12_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S12_AXI_arvalid : IN STD_LOGIC;
    S12_AXI_arready : OUT STD_LOGIC;
    S12_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S12_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S12_AXI_rlast : OUT STD_LOGIC;
    S12_AXI_rvalid : OUT STD_LOGIC;
    S12_AXI_rready : IN STD_LOGIC;
    S13_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S13_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S13_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S13_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S13_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S13_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S13_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S13_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S13_AXI_arvalid : IN STD_LOGIC;
    S13_AXI_arready : OUT STD_LOGIC;
    S13_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S13_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S13_AXI_rlast : OUT STD_LOGIC;
    S13_AXI_rvalid : OUT STD_LOGIC;
    S13_AXI_rready : IN STD_LOGIC;
    S14_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S14_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S14_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S14_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S14_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S14_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S14_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S14_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S14_AXI_arvalid : IN STD_LOGIC;
    S14_AXI_arready : OUT STD_LOGIC;
    S14_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    S14_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S14_AXI_rlast : OUT STD_LOGIC;
    S14_AXI_rvalid : OUT STD_LOGIC;
    S14_AXI_rready : IN STD_LOGIC;
    S15_AXI_awaddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S15_AXI_awlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    S15_AXI_awsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S15_AXI_awburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S15_AXI_awlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    S15_AXI_awcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S15_AXI_awprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    S15_AXI_awqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S15_AXI_awvalid : IN STD_LOGIC;
    S15_AXI_awready : OUT STD_LOGIC;
    S15_AXI_wdata : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    S15_AXI_wstrb : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    S15_AXI_wlast : IN STD_LOGIC;
    S15_AXI_wvalid : IN STD_LOGIC;
    S15_AXI_wready : OUT STD_LOGIC;
    S15_AXI_bresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    S15_AXI_bvalid : OUT STD_LOGIC;
    S15_AXI_bready : IN STD_LOGIC;
    M00_AXI_awaddr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    M00_AXI_awlen : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    M00_AXI_awsize : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    M00_AXI_awburst : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    M00_AXI_awlock : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    M00_AXI_awcache : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    M00_AXI_awprot : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    M00_AXI_awqos : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    M00_AXI_awvalid : OUT STD_LOGIC;
    M00_AXI_awready : IN STD_LOGIC;
    M00_AXI_wdata : OUT STD_LOGIC_VECTOR(63 DOWNTO 0);
    M00_AXI_wstrb : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    M00_AXI_wlast : OUT STD_LOGIC;
    M00_AXI_wvalid : OUT STD_LOGIC;
    M00_AXI_wready : IN STD_LOGIC;
    M00_AXI_bresp : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    M00_AXI_bvalid : IN STD_LOGIC;
    M00_AXI_bready : OUT STD_LOGIC;
    M00_AXI_araddr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    M00_AXI_arlen : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    M00_AXI_arsize : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    M00_AXI_arburst : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    M00_AXI_arlock : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    M00_AXI_arcache : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    M00_AXI_arprot : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    M00_AXI_arqos : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    M00_AXI_arvalid : OUT STD_LOGIC;
    M00_AXI_arready : IN STD_LOGIC;
    M00_AXI_rdata : IN STD_LOGIC_VECTOR(63 DOWNTO 0);
    M00_AXI_rresp : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    M00_AXI_rlast : IN STD_LOGIC;
    M00_AXI_rvalid : IN STD_LOGIC;
    M00_AXI_rready : OUT STD_LOGIC
  );
END version1_stream_interconnect_0;

ARCHITECTURE version1_stream_interconnect_0_arch OF version1_stream_interconnect_0 IS
  ATTRIBUTE DowngradeIPIdentifiedWarnings : STRING;
  ATTRIBUTE DowngradeIPIdentifiedWarnings OF version1_stream_interconnect_0_arch: ARCHITECTURE IS "yes";
  COMPONENT bd_8ee2 IS
    PORT (
      aclk : IN STD_LOGIC;
      aresetn : IN STD_LOGIC;
      S00_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S00_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S00_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S00_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S00_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S00_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S00_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S00_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S00_AXI_arvalid : IN STD_LOGIC;
      S00_AXI_arready : OUT STD_LOGIC;
      S00_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S00_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S00_AXI_rlast : OUT STD_LOGIC;
      S00_AXI_rvalid : OUT STD_LOGIC;
      S00_AXI_rready : IN STD_LOGIC;
      S01_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S01_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S01_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S01_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S01_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S01_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S01_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S01_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S01_AXI_arvalid : IN STD_LOGIC;
      S01_AXI_arready : OUT STD_LOGIC;
      S01_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S01_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S01_AXI_rlast : OUT STD_LOGIC;
      S01_AXI_rvalid : OUT STD_LOGIC;
      S01_AXI_rready : IN STD_LOGIC;
      S02_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S02_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S02_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S02_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S02_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S02_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S02_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S02_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S02_AXI_arvalid : IN STD_LOGIC;
      S02_AXI_arready : OUT STD_LOGIC;
      S02_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S02_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S02_AXI_rlast : OUT STD_LOGIC;
      S02_AXI_rvalid : OUT STD_LOGIC;
      S02_AXI_rready : IN STD_LOGIC;
      S03_AXI_awaddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S03_AXI_awlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S03_AXI_awsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S03_AXI_awburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S03_AXI_awlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S03_AXI_awcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S03_AXI_awprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S03_AXI_awqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S03_AXI_awvalid : IN STD_LOGIC;
      S03_AXI_awready : OUT STD_LOGIC;
      S03_AXI_wdata : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S03_AXI_wstrb : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S03_AXI_wlast : IN STD_LOGIC;
      S03_AXI_wvalid : IN STD_LOGIC;
      S03_AXI_wready : OUT STD_LOGIC;
      S03_AXI_bresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S03_AXI_bvalid : OUT STD_LOGIC;
      S03_AXI_bready : IN STD_LOGIC;
      S04_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S04_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S04_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S04_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S04_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S04_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S04_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S04_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S04_AXI_arvalid : IN STD_LOGIC;
      S04_AXI_arready : OUT STD_LOGIC;
      S04_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S04_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S04_AXI_rlast : OUT STD_LOGIC;
      S04_AXI_rvalid : OUT STD_LOGIC;
      S04_AXI_rready : IN STD_LOGIC;
      S05_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S05_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S05_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S05_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S05_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S05_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S05_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S05_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S05_AXI_arvalid : IN STD_LOGIC;
      S05_AXI_arready : OUT STD_LOGIC;
      S05_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S05_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S05_AXI_rlast : OUT STD_LOGIC;
      S05_AXI_rvalid : OUT STD_LOGIC;
      S05_AXI_rready : IN STD_LOGIC;
      S06_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S06_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S06_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S06_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S06_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S06_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S06_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S06_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S06_AXI_arvalid : IN STD_LOGIC;
      S06_AXI_arready : OUT STD_LOGIC;
      S06_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S06_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S06_AXI_rlast : OUT STD_LOGIC;
      S06_AXI_rvalid : OUT STD_LOGIC;
      S06_AXI_rready : IN STD_LOGIC;
      S07_AXI_awaddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S07_AXI_awlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S07_AXI_awsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S07_AXI_awburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S07_AXI_awlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S07_AXI_awcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S07_AXI_awprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S07_AXI_awqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S07_AXI_awvalid : IN STD_LOGIC;
      S07_AXI_awready : OUT STD_LOGIC;
      S07_AXI_wdata : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S07_AXI_wstrb : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S07_AXI_wlast : IN STD_LOGIC;
      S07_AXI_wvalid : IN STD_LOGIC;
      S07_AXI_wready : OUT STD_LOGIC;
      S07_AXI_bresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S07_AXI_bvalid : OUT STD_LOGIC;
      S07_AXI_bready : IN STD_LOGIC;
      S08_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S08_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S08_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S08_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S08_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S08_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S08_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S08_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S08_AXI_arvalid : IN STD_LOGIC;
      S08_AXI_arready : OUT STD_LOGIC;
      S08_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S08_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S08_AXI_rlast : OUT STD_LOGIC;
      S08_AXI_rvalid : OUT STD_LOGIC;
      S08_AXI_rready : IN STD_LOGIC;
      S09_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S09_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S09_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S09_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S09_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S09_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S09_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S09_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S09_AXI_arvalid : IN STD_LOGIC;
      S09_AXI_arready : OUT STD_LOGIC;
      S09_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S09_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S09_AXI_rlast : OUT STD_LOGIC;
      S09_AXI_rvalid : OUT STD_LOGIC;
      S09_AXI_rready : IN STD_LOGIC;
      S10_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S10_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S10_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S10_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S10_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S10_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S10_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S10_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S10_AXI_arvalid : IN STD_LOGIC;
      S10_AXI_arready : OUT STD_LOGIC;
      S10_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S10_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S10_AXI_rlast : OUT STD_LOGIC;
      S10_AXI_rvalid : OUT STD_LOGIC;
      S10_AXI_rready : IN STD_LOGIC;
      S11_AXI_awaddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S11_AXI_awlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S11_AXI_awsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S11_AXI_awburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S11_AXI_awlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S11_AXI_awcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S11_AXI_awprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S11_AXI_awqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S11_AXI_awvalid : IN STD_LOGIC;
      S11_AXI_awready : OUT STD_LOGIC;
      S11_AXI_wdata : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S11_AXI_wstrb : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S11_AXI_wlast : IN STD_LOGIC;
      S11_AXI_wvalid : IN STD_LOGIC;
      S11_AXI_wready : OUT STD_LOGIC;
      S11_AXI_bresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S11_AXI_bvalid : OUT STD_LOGIC;
      S11_AXI_bready : IN STD_LOGIC;
      S12_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S12_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S12_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S12_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S12_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S12_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S12_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S12_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S12_AXI_arvalid : IN STD_LOGIC;
      S12_AXI_arready : OUT STD_LOGIC;
      S12_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S12_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S12_AXI_rlast : OUT STD_LOGIC;
      S12_AXI_rvalid : OUT STD_LOGIC;
      S12_AXI_rready : IN STD_LOGIC;
      S13_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S13_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S13_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S13_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S13_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S13_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S13_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S13_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S13_AXI_arvalid : IN STD_LOGIC;
      S13_AXI_arready : OUT STD_LOGIC;
      S13_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S13_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S13_AXI_rlast : OUT STD_LOGIC;
      S13_AXI_rvalid : OUT STD_LOGIC;
      S13_AXI_rready : IN STD_LOGIC;
      S14_AXI_araddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S14_AXI_arlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S14_AXI_arsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S14_AXI_arburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S14_AXI_arlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S14_AXI_arcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S14_AXI_arprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S14_AXI_arqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S14_AXI_arvalid : IN STD_LOGIC;
      S14_AXI_arready : OUT STD_LOGIC;
      S14_AXI_rdata : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      S14_AXI_rresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S14_AXI_rlast : OUT STD_LOGIC;
      S14_AXI_rvalid : OUT STD_LOGIC;
      S14_AXI_rready : IN STD_LOGIC;
      S15_AXI_awaddr : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S15_AXI_awlen : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
      S15_AXI_awsize : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S15_AXI_awburst : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      S15_AXI_awlock : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      S15_AXI_awcache : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S15_AXI_awprot : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      S15_AXI_awqos : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S15_AXI_awvalid : IN STD_LOGIC;
      S15_AXI_awready : OUT STD_LOGIC;
      S15_AXI_wdata : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      S15_AXI_wstrb : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      S15_AXI_wlast : IN STD_LOGIC;
      S15_AXI_wvalid : IN STD_LOGIC;
      S15_AXI_wready : OUT STD_LOGIC;
      S15_AXI_bresp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      S15_AXI_bvalid : OUT STD_LOGIC;
      S15_AXI_bready : IN STD_LOGIC;
      M00_AXI_awaddr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      M00_AXI_awlen : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      M00_AXI_awsize : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      M00_AXI_awburst : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      M00_AXI_awlock : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      M00_AXI_awcache : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      M00_AXI_awprot : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      M00_AXI_awqos : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      M00_AXI_awvalid : OUT STD_LOGIC;
      M00_AXI_awready : IN STD_LOGIC;
      M00_AXI_wdata : OUT STD_LOGIC_VECTOR(63 DOWNTO 0);
      M00_AXI_wstrb : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      M00_AXI_wlast : OUT STD_LOGIC;
      M00_AXI_wvalid : OUT STD_LOGIC;
      M00_AXI_wready : IN STD_LOGIC;
      M00_AXI_bresp : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      M00_AXI_bvalid : IN STD_LOGIC;
      M00_AXI_bready : OUT STD_LOGIC;
      M00_AXI_araddr : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      M00_AXI_arlen : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      M00_AXI_arsize : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      M00_AXI_arburst : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      M00_AXI_arlock : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      M00_AXI_arcache : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      M00_AXI_arprot : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      M00_AXI_arqos : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      M00_AXI_arvalid : OUT STD_LOGIC;
      M00_AXI_arready : IN STD_LOGIC;
      M00_AXI_rdata : IN STD_LOGIC_VECTOR(63 DOWNTO 0);
      M00_AXI_rresp : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      M00_AXI_rlast : IN STD_LOGIC;
      M00_AXI_rvalid : IN STD_LOGIC;
      M00_AXI_rready : OUT STD_LOGIC
    );
  END COMPONENT bd_8ee2;
  ATTRIBUTE X_INTERFACE_INFO : STRING;
  ATTRIBUTE X_INTERFACE_PARAMETER : STRING;
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_rready: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_rvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_rlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_rresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_rdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_arready: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_arvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_arqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_arprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_arcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_arlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_arburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_arsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_arlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI ARLEN";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_araddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_bready: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_bvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_bresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_wready: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_wvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_wlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_wstrb: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_wdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_awready: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_awvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_awqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_awprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_awcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_awlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_awburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_awsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_awlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF M00_AXI_awaddr: SIGNAL IS "XIL_INTERFACENAME M00_AXI, DATA_WIDTH 64, PROTOCOL AXI3, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_BURST_LENGTH 8, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREAD" & 
"S 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF M00_AXI_awaddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 M00_AXI AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_bready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_bvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_bresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_wready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_wvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_wlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_wstrb: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_wdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_awready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_awvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_awqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_awprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_awcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_awlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_awburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_awsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_awlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S15_AXI_awaddr: SIGNAL IS "XIL_INTERFACENAME S15_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 0, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 16, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREAD" & 
"S 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S15_AXI_awaddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S15_AXI AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S14_AXI_rready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S14_AXI RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S14_AXI_rvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S14_AXI RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S14_AXI_rlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S14_AXI RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S14_AXI_rresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S14_AXI RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S14_AXI_rdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S14_AXI RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S14_AXI_arready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S14_AXI ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S14_AXI_arvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S14_AXI ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S14_AXI_arqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S14_AXI ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S14_AXI_arprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S14_AXI ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S14_AXI_arcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S14_AXI ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S14_AXI_arlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S14_AXI ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S14_AXI_arburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S14_AXI ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S14_AXI_arsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S14_AXI ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S14_AXI_arlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S14_AXI ARLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S14_AXI_araddr: SIGNAL IS "XIL_INTERFACENAME S14_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 0, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREADS" & 
" 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S14_AXI_araddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S14_AXI ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S13_AXI_rready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S13_AXI RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S13_AXI_rvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S13_AXI RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S13_AXI_rlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S13_AXI RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S13_AXI_rresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S13_AXI RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S13_AXI_rdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S13_AXI RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S13_AXI_arready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S13_AXI ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S13_AXI_arvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S13_AXI ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S13_AXI_arqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S13_AXI ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S13_AXI_arprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S13_AXI ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S13_AXI_arcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S13_AXI ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S13_AXI_arlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S13_AXI ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S13_AXI_arburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S13_AXI ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S13_AXI_arsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S13_AXI ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S13_AXI_arlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S13_AXI ARLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S13_AXI_araddr: SIGNAL IS "XIL_INTERFACENAME S13_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 0, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREADS" & 
" 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S13_AXI_araddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S13_AXI ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S12_AXI_rready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S12_AXI RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S12_AXI_rvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S12_AXI RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S12_AXI_rlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S12_AXI RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S12_AXI_rresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S12_AXI RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S12_AXI_rdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S12_AXI RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S12_AXI_arready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S12_AXI ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S12_AXI_arvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S12_AXI ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S12_AXI_arqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S12_AXI ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S12_AXI_arprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S12_AXI ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S12_AXI_arcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S12_AXI ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S12_AXI_arlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S12_AXI ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S12_AXI_arburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S12_AXI ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S12_AXI_arsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S12_AXI ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S12_AXI_arlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S12_AXI ARLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S12_AXI_araddr: SIGNAL IS "XIL_INTERFACENAME S12_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 0, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREADS" & 
" 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S12_AXI_araddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S12_AXI ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_bready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_bvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_bresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_wready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_wvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_wlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_wstrb: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_wdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_awready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_awvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_awqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_awprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_awcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_awlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_awburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_awsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_awlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S11_AXI_awaddr: SIGNAL IS "XIL_INTERFACENAME S11_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 0, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 16, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREAD" & 
"S 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S11_AXI_awaddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S11_AXI AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S10_AXI_rready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S10_AXI RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S10_AXI_rvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S10_AXI RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S10_AXI_rlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S10_AXI RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S10_AXI_rresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S10_AXI RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S10_AXI_rdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S10_AXI RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S10_AXI_arready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S10_AXI ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S10_AXI_arvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S10_AXI ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S10_AXI_arqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S10_AXI ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S10_AXI_arprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S10_AXI ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S10_AXI_arcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S10_AXI ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S10_AXI_arlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S10_AXI ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S10_AXI_arburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S10_AXI ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S10_AXI_arsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S10_AXI ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S10_AXI_arlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S10_AXI ARLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S10_AXI_araddr: SIGNAL IS "XIL_INTERFACENAME S10_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 0, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREADS" & 
" 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S10_AXI_araddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S10_AXI ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S09_AXI_rready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S09_AXI RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S09_AXI_rvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S09_AXI RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S09_AXI_rlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S09_AXI RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S09_AXI_rresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S09_AXI RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S09_AXI_rdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S09_AXI RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S09_AXI_arready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S09_AXI ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S09_AXI_arvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S09_AXI ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S09_AXI_arqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S09_AXI ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S09_AXI_arprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S09_AXI ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S09_AXI_arcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S09_AXI ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S09_AXI_arlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S09_AXI ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S09_AXI_arburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S09_AXI ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S09_AXI_arsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S09_AXI ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S09_AXI_arlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S09_AXI ARLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S09_AXI_araddr: SIGNAL IS "XIL_INTERFACENAME S09_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 0, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREADS" & 
" 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S09_AXI_araddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S09_AXI ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S08_AXI_rready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S08_AXI RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S08_AXI_rvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S08_AXI RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S08_AXI_rlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S08_AXI RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S08_AXI_rresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S08_AXI RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S08_AXI_rdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S08_AXI RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S08_AXI_arready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S08_AXI ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S08_AXI_arvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S08_AXI ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S08_AXI_arqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S08_AXI ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S08_AXI_arprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S08_AXI ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S08_AXI_arcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S08_AXI ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S08_AXI_arlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S08_AXI ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S08_AXI_arburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S08_AXI ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S08_AXI_arsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S08_AXI ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S08_AXI_arlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S08_AXI ARLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S08_AXI_araddr: SIGNAL IS "XIL_INTERFACENAME S08_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 0, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREADS" & 
" 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S08_AXI_araddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S08_AXI ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_bready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_bvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_bresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_wready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_wvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_wlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_wstrb: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_wdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_awready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_awvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_awqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_awprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_awcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_awlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_awburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_awsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_awlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S07_AXI_awaddr: SIGNAL IS "XIL_INTERFACENAME S07_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 0, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 16, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREAD" & 
"S 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S07_AXI_awaddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S07_AXI AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S06_AXI_rready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S06_AXI RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S06_AXI_rvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S06_AXI RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S06_AXI_rlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S06_AXI RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S06_AXI_rresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S06_AXI RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S06_AXI_rdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S06_AXI RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S06_AXI_arready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S06_AXI ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S06_AXI_arvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S06_AXI ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S06_AXI_arqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S06_AXI ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S06_AXI_arprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S06_AXI ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S06_AXI_arcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S06_AXI ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S06_AXI_arlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S06_AXI ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S06_AXI_arburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S06_AXI ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S06_AXI_arsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S06_AXI ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S06_AXI_arlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S06_AXI ARLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S06_AXI_araddr: SIGNAL IS "XIL_INTERFACENAME S06_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 0, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREADS" & 
" 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S06_AXI_araddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S06_AXI ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S05_AXI_rready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S05_AXI RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S05_AXI_rvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S05_AXI RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S05_AXI_rlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S05_AXI RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S05_AXI_rresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S05_AXI RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S05_AXI_rdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S05_AXI RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S05_AXI_arready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S05_AXI ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S05_AXI_arvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S05_AXI ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S05_AXI_arqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S05_AXI ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S05_AXI_arprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S05_AXI ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S05_AXI_arcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S05_AXI ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S05_AXI_arlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S05_AXI ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S05_AXI_arburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S05_AXI ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S05_AXI_arsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S05_AXI ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S05_AXI_arlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S05_AXI ARLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S05_AXI_araddr: SIGNAL IS "XIL_INTERFACENAME S05_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 0, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREADS" & 
" 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S05_AXI_araddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S05_AXI ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S04_AXI_rready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S04_AXI RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S04_AXI_rvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S04_AXI RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S04_AXI_rlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S04_AXI RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S04_AXI_rresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S04_AXI RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S04_AXI_rdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S04_AXI RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S04_AXI_arready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S04_AXI ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S04_AXI_arvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S04_AXI ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S04_AXI_arqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S04_AXI ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S04_AXI_arprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S04_AXI ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S04_AXI_arcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S04_AXI ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S04_AXI_arlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S04_AXI ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S04_AXI_arburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S04_AXI ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S04_AXI_arsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S04_AXI ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S04_AXI_arlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S04_AXI ARLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S04_AXI_araddr: SIGNAL IS "XIL_INTERFACENAME S04_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 0, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREADS" & 
" 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S04_AXI_araddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S04_AXI ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_bready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_bvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_bresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_wready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_wvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_wlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_wstrb: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_wdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_awready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_awvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_awqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_awprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_awcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_awlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_awburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_awsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_awlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S03_AXI_awaddr: SIGNAL IS "XIL_INTERFACENAME S03_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 0, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 16, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREAD" & 
"S 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S03_AXI_awaddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S03_AXI AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S02_AXI_rready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S02_AXI RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S02_AXI_rvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S02_AXI RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S02_AXI_rlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S02_AXI RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S02_AXI_rresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S02_AXI RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S02_AXI_rdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S02_AXI RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S02_AXI_arready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S02_AXI ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S02_AXI_arvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S02_AXI ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S02_AXI_arqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S02_AXI ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S02_AXI_arprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S02_AXI ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S02_AXI_arcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S02_AXI ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S02_AXI_arlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S02_AXI ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S02_AXI_arburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S02_AXI ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S02_AXI_arsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S02_AXI ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S02_AXI_arlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S02_AXI ARLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S02_AXI_araddr: SIGNAL IS "XIL_INTERFACENAME S02_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 0, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREADS" & 
" 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S02_AXI_araddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S02_AXI ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S01_AXI_rready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S01_AXI RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S01_AXI_rvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S01_AXI RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S01_AXI_rlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S01_AXI RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S01_AXI_rresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S01_AXI RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S01_AXI_rdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S01_AXI RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S01_AXI_arready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S01_AXI ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S01_AXI_arvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S01_AXI ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S01_AXI_arqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S01_AXI ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S01_AXI_arprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S01_AXI ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S01_AXI_arcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S01_AXI ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S01_AXI_arlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S01_AXI ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S01_AXI_arburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S01_AXI ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S01_AXI_arsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S01_AXI ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S01_AXI_arlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S01_AXI ARLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S01_AXI_araddr: SIGNAL IS "XIL_INTERFACENAME S01_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 0, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREADS" & 
" 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S01_AXI_araddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S01_AXI ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF S00_AXI_rready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S00_AXI RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S00_AXI_rvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S00_AXI RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S00_AXI_rlast: SIGNAL IS "xilinx.com:interface:aximm:1.0 S00_AXI RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF S00_AXI_rresp: SIGNAL IS "xilinx.com:interface:aximm:1.0 S00_AXI RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF S00_AXI_rdata: SIGNAL IS "xilinx.com:interface:aximm:1.0 S00_AXI RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF S00_AXI_arready: SIGNAL IS "xilinx.com:interface:aximm:1.0 S00_AXI ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF S00_AXI_arvalid: SIGNAL IS "xilinx.com:interface:aximm:1.0 S00_AXI ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF S00_AXI_arqos: SIGNAL IS "xilinx.com:interface:aximm:1.0 S00_AXI ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF S00_AXI_arprot: SIGNAL IS "xilinx.com:interface:aximm:1.0 S00_AXI ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF S00_AXI_arcache: SIGNAL IS "xilinx.com:interface:aximm:1.0 S00_AXI ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF S00_AXI_arlock: SIGNAL IS "xilinx.com:interface:aximm:1.0 S00_AXI ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF S00_AXI_arburst: SIGNAL IS "xilinx.com:interface:aximm:1.0 S00_AXI ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF S00_AXI_arsize: SIGNAL IS "xilinx.com:interface:aximm:1.0 S00_AXI ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF S00_AXI_arlen: SIGNAL IS "xilinx.com:interface:aximm:1.0 S00_AXI ARLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF S00_AXI_araddr: SIGNAL IS "XIL_INTERFACENAME S00_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 0, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, NUM_READ_THREADS" & 
" 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF S00_AXI_araddr: SIGNAL IS "xilinx.com:interface:aximm:1.0 S00_AXI ARADDR";
  ATTRIBUTE X_INTERFACE_PARAMETER OF aresetn: SIGNAL IS "XIL_INTERFACENAME RST.aresetn, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF aresetn: SIGNAL IS "xilinx.com:signal:reset:1.0 RST.aresetn RST";
  ATTRIBUTE X_INTERFACE_PARAMETER OF aclk: SIGNAL IS "XIL_INTERFACENAME CLK.aclk, FREQ_HZ 100000000, PHASE 0.000, CLK_DOMAIN version1_processing_system7_0_1_FCLK_CLK0, ASSOCIATED_BUSIF M00_AXI:S00_AXI:S01_AXI:S02_AXI:S03_AXI:S04_AXI:S05_AXI:S06_AXI:S07_AXI:S08_AXI:S09_AXI:S10_AXI:S11_AXI:S12_AXI:S13_AXI:S14_AXI:S15_AXI, INSERT_VIP 0, ASSOCIATED_CLKEN m_sc_aclken";
  ATTRIBUTE X_INTERFACE_INFO OF aclk: SIGNAL IS "xilinx.com:signal:clock:1.0 CLK.aclk CLK";
BEGIN
  U0 : bd_8ee2
    PORT MAP (
      aclk => aclk,
      aresetn => aresetn,
      S00_AXI_araddr => S00_AXI_araddr,
      S00_AXI_arlen => S00_AXI_arlen,
      S00_AXI_arsize => S00_AXI_arsize,
      S00_AXI_arburst => S00_AXI_arburst,
      S00_AXI_arlock => S00_AXI_arlock,
      S00_AXI_arcache => S00_AXI_arcache,
      S00_AXI_arprot => S00_AXI_arprot,
      S00_AXI_arqos => S00_AXI_arqos,
      S00_AXI_arvalid => S00_AXI_arvalid,
      S00_AXI_arready => S00_AXI_arready,
      S00_AXI_rdata => S00_AXI_rdata,
      S00_AXI_rresp => S00_AXI_rresp,
      S00_AXI_rlast => S00_AXI_rlast,
      S00_AXI_rvalid => S00_AXI_rvalid,
      S00_AXI_rready => S00_AXI_rready,
      S01_AXI_araddr => S01_AXI_araddr,
      S01_AXI_arlen => S01_AXI_arlen,
      S01_AXI_arsize => S01_AXI_arsize,
      S01_AXI_arburst => S01_AXI_arburst,
      S01_AXI_arlock => S01_AXI_arlock,
      S01_AXI_arcache => S01_AXI_arcache,
      S01_AXI_arprot => S01_AXI_arprot,
      S01_AXI_arqos => S01_AXI_arqos,
      S01_AXI_arvalid => S01_AXI_arvalid,
      S01_AXI_arready => S01_AXI_arready,
      S01_AXI_rdata => S01_AXI_rdata,
      S01_AXI_rresp => S01_AXI_rresp,
      S01_AXI_rlast => S01_AXI_rlast,
      S01_AXI_rvalid => S01_AXI_rvalid,
      S01_AXI_rready => S01_AXI_rready,
      S02_AXI_araddr => S02_AXI_araddr,
      S02_AXI_arlen => S02_AXI_arlen,
      S02_AXI_arsize => S02_AXI_arsize,
      S02_AXI_arburst => S02_AXI_arburst,
      S02_AXI_arlock => S02_AXI_arlock,
      S02_AXI_arcache => S02_AXI_arcache,
      S02_AXI_arprot => S02_AXI_arprot,
      S02_AXI_arqos => S02_AXI_arqos,
      S02_AXI_arvalid => S02_AXI_arvalid,
      S02_AXI_arready => S02_AXI_arready,
      S02_AXI_rdata => S02_AXI_rdata,
      S02_AXI_rresp => S02_AXI_rresp,
      S02_AXI_rlast => S02_AXI_rlast,
      S02_AXI_rvalid => S02_AXI_rvalid,
      S02_AXI_rready => S02_AXI_rready,
      S03_AXI_awaddr => S03_AXI_awaddr,
      S03_AXI_awlen => S03_AXI_awlen,
      S03_AXI_awsize => S03_AXI_awsize,
      S03_AXI_awburst => S03_AXI_awburst,
      S03_AXI_awlock => S03_AXI_awlock,
      S03_AXI_awcache => S03_AXI_awcache,
      S03_AXI_awprot => S03_AXI_awprot,
      S03_AXI_awqos => S03_AXI_awqos,
      S03_AXI_awvalid => S03_AXI_awvalid,
      S03_AXI_awready => S03_AXI_awready,
      S03_AXI_wdata => S03_AXI_wdata,
      S03_AXI_wstrb => S03_AXI_wstrb,
      S03_AXI_wlast => S03_AXI_wlast,
      S03_AXI_wvalid => S03_AXI_wvalid,
      S03_AXI_wready => S03_AXI_wready,
      S03_AXI_bresp => S03_AXI_bresp,
      S03_AXI_bvalid => S03_AXI_bvalid,
      S03_AXI_bready => S03_AXI_bready,
      S04_AXI_araddr => S04_AXI_araddr,
      S04_AXI_arlen => S04_AXI_arlen,
      S04_AXI_arsize => S04_AXI_arsize,
      S04_AXI_arburst => S04_AXI_arburst,
      S04_AXI_arlock => S04_AXI_arlock,
      S04_AXI_arcache => S04_AXI_arcache,
      S04_AXI_arprot => S04_AXI_arprot,
      S04_AXI_arqos => S04_AXI_arqos,
      S04_AXI_arvalid => S04_AXI_arvalid,
      S04_AXI_arready => S04_AXI_arready,
      S04_AXI_rdata => S04_AXI_rdata,
      S04_AXI_rresp => S04_AXI_rresp,
      S04_AXI_rlast => S04_AXI_rlast,
      S04_AXI_rvalid => S04_AXI_rvalid,
      S04_AXI_rready => S04_AXI_rready,
      S05_AXI_araddr => S05_AXI_araddr,
      S05_AXI_arlen => S05_AXI_arlen,
      S05_AXI_arsize => S05_AXI_arsize,
      S05_AXI_arburst => S05_AXI_arburst,
      S05_AXI_arlock => S05_AXI_arlock,
      S05_AXI_arcache => S05_AXI_arcache,
      S05_AXI_arprot => S05_AXI_arprot,
      S05_AXI_arqos => S05_AXI_arqos,
      S05_AXI_arvalid => S05_AXI_arvalid,
      S05_AXI_arready => S05_AXI_arready,
      S05_AXI_rdata => S05_AXI_rdata,
      S05_AXI_rresp => S05_AXI_rresp,
      S05_AXI_rlast => S05_AXI_rlast,
      S05_AXI_rvalid => S05_AXI_rvalid,
      S05_AXI_rready => S05_AXI_rready,
      S06_AXI_araddr => S06_AXI_araddr,
      S06_AXI_arlen => S06_AXI_arlen,
      S06_AXI_arsize => S06_AXI_arsize,
      S06_AXI_arburst => S06_AXI_arburst,
      S06_AXI_arlock => S06_AXI_arlock,
      S06_AXI_arcache => S06_AXI_arcache,
      S06_AXI_arprot => S06_AXI_arprot,
      S06_AXI_arqos => S06_AXI_arqos,
      S06_AXI_arvalid => S06_AXI_arvalid,
      S06_AXI_arready => S06_AXI_arready,
      S06_AXI_rdata => S06_AXI_rdata,
      S06_AXI_rresp => S06_AXI_rresp,
      S06_AXI_rlast => S06_AXI_rlast,
      S06_AXI_rvalid => S06_AXI_rvalid,
      S06_AXI_rready => S06_AXI_rready,
      S07_AXI_awaddr => S07_AXI_awaddr,
      S07_AXI_awlen => S07_AXI_awlen,
      S07_AXI_awsize => S07_AXI_awsize,
      S07_AXI_awburst => S07_AXI_awburst,
      S07_AXI_awlock => S07_AXI_awlock,
      S07_AXI_awcache => S07_AXI_awcache,
      S07_AXI_awprot => S07_AXI_awprot,
      S07_AXI_awqos => S07_AXI_awqos,
      S07_AXI_awvalid => S07_AXI_awvalid,
      S07_AXI_awready => S07_AXI_awready,
      S07_AXI_wdata => S07_AXI_wdata,
      S07_AXI_wstrb => S07_AXI_wstrb,
      S07_AXI_wlast => S07_AXI_wlast,
      S07_AXI_wvalid => S07_AXI_wvalid,
      S07_AXI_wready => S07_AXI_wready,
      S07_AXI_bresp => S07_AXI_bresp,
      S07_AXI_bvalid => S07_AXI_bvalid,
      S07_AXI_bready => S07_AXI_bready,
      S08_AXI_araddr => S08_AXI_araddr,
      S08_AXI_arlen => S08_AXI_arlen,
      S08_AXI_arsize => S08_AXI_arsize,
      S08_AXI_arburst => S08_AXI_arburst,
      S08_AXI_arlock => S08_AXI_arlock,
      S08_AXI_arcache => S08_AXI_arcache,
      S08_AXI_arprot => S08_AXI_arprot,
      S08_AXI_arqos => S08_AXI_arqos,
      S08_AXI_arvalid => S08_AXI_arvalid,
      S08_AXI_arready => S08_AXI_arready,
      S08_AXI_rdata => S08_AXI_rdata,
      S08_AXI_rresp => S08_AXI_rresp,
      S08_AXI_rlast => S08_AXI_rlast,
      S08_AXI_rvalid => S08_AXI_rvalid,
      S08_AXI_rready => S08_AXI_rready,
      S09_AXI_araddr => S09_AXI_araddr,
      S09_AXI_arlen => S09_AXI_arlen,
      S09_AXI_arsize => S09_AXI_arsize,
      S09_AXI_arburst => S09_AXI_arburst,
      S09_AXI_arlock => S09_AXI_arlock,
      S09_AXI_arcache => S09_AXI_arcache,
      S09_AXI_arprot => S09_AXI_arprot,
      S09_AXI_arqos => S09_AXI_arqos,
      S09_AXI_arvalid => S09_AXI_arvalid,
      S09_AXI_arready => S09_AXI_arready,
      S09_AXI_rdata => S09_AXI_rdata,
      S09_AXI_rresp => S09_AXI_rresp,
      S09_AXI_rlast => S09_AXI_rlast,
      S09_AXI_rvalid => S09_AXI_rvalid,
      S09_AXI_rready => S09_AXI_rready,
      S10_AXI_araddr => S10_AXI_araddr,
      S10_AXI_arlen => S10_AXI_arlen,
      S10_AXI_arsize => S10_AXI_arsize,
      S10_AXI_arburst => S10_AXI_arburst,
      S10_AXI_arlock => S10_AXI_arlock,
      S10_AXI_arcache => S10_AXI_arcache,
      S10_AXI_arprot => S10_AXI_arprot,
      S10_AXI_arqos => S10_AXI_arqos,
      S10_AXI_arvalid => S10_AXI_arvalid,
      S10_AXI_arready => S10_AXI_arready,
      S10_AXI_rdata => S10_AXI_rdata,
      S10_AXI_rresp => S10_AXI_rresp,
      S10_AXI_rlast => S10_AXI_rlast,
      S10_AXI_rvalid => S10_AXI_rvalid,
      S10_AXI_rready => S10_AXI_rready,
      S11_AXI_awaddr => S11_AXI_awaddr,
      S11_AXI_awlen => S11_AXI_awlen,
      S11_AXI_awsize => S11_AXI_awsize,
      S11_AXI_awburst => S11_AXI_awburst,
      S11_AXI_awlock => S11_AXI_awlock,
      S11_AXI_awcache => S11_AXI_awcache,
      S11_AXI_awprot => S11_AXI_awprot,
      S11_AXI_awqos => S11_AXI_awqos,
      S11_AXI_awvalid => S11_AXI_awvalid,
      S11_AXI_awready => S11_AXI_awready,
      S11_AXI_wdata => S11_AXI_wdata,
      S11_AXI_wstrb => S11_AXI_wstrb,
      S11_AXI_wlast => S11_AXI_wlast,
      S11_AXI_wvalid => S11_AXI_wvalid,
      S11_AXI_wready => S11_AXI_wready,
      S11_AXI_bresp => S11_AXI_bresp,
      S11_AXI_bvalid => S11_AXI_bvalid,
      S11_AXI_bready => S11_AXI_bready,
      S12_AXI_araddr => S12_AXI_araddr,
      S12_AXI_arlen => S12_AXI_arlen,
      S12_AXI_arsize => S12_AXI_arsize,
      S12_AXI_arburst => S12_AXI_arburst,
      S12_AXI_arlock => S12_AXI_arlock,
      S12_AXI_arcache => S12_AXI_arcache,
      S12_AXI_arprot => S12_AXI_arprot,
      S12_AXI_arqos => S12_AXI_arqos,
      S12_AXI_arvalid => S12_AXI_arvalid,
      S12_AXI_arready => S12_AXI_arready,
      S12_AXI_rdata => S12_AXI_rdata,
      S12_AXI_rresp => S12_AXI_rresp,
      S12_AXI_rlast => S12_AXI_rlast,
      S12_AXI_rvalid => S12_AXI_rvalid,
      S12_AXI_rready => S12_AXI_rready,
      S13_AXI_araddr => S13_AXI_araddr,
      S13_AXI_arlen => S13_AXI_arlen,
      S13_AXI_arsize => S13_AXI_arsize,
      S13_AXI_arburst => S13_AXI_arburst,
      S13_AXI_arlock => S13_AXI_arlock,
      S13_AXI_arcache => S13_AXI_arcache,
      S13_AXI_arprot => S13_AXI_arprot,
      S13_AXI_arqos => S13_AXI_arqos,
      S13_AXI_arvalid => S13_AXI_arvalid,
      S13_AXI_arready => S13_AXI_arready,
      S13_AXI_rdata => S13_AXI_rdata,
      S13_AXI_rresp => S13_AXI_rresp,
      S13_AXI_rlast => S13_AXI_rlast,
      S13_AXI_rvalid => S13_AXI_rvalid,
      S13_AXI_rready => S13_AXI_rready,
      S14_AXI_araddr => S14_AXI_araddr,
      S14_AXI_arlen => S14_AXI_arlen,
      S14_AXI_arsize => S14_AXI_arsize,
      S14_AXI_arburst => S14_AXI_arburst,
      S14_AXI_arlock => S14_AXI_arlock,
      S14_AXI_arcache => S14_AXI_arcache,
      S14_AXI_arprot => S14_AXI_arprot,
      S14_AXI_arqos => S14_AXI_arqos,
      S14_AXI_arvalid => S14_AXI_arvalid,
      S14_AXI_arready => S14_AXI_arready,
      S14_AXI_rdata => S14_AXI_rdata,
      S14_AXI_rresp => S14_AXI_rresp,
      S14_AXI_rlast => S14_AXI_rlast,
      S14_AXI_rvalid => S14_AXI_rvalid,
      S14_AXI_rready => S14_AXI_rready,
      S15_AXI_awaddr => S15_AXI_awaddr,
      S15_AXI_awlen => S15_AXI_awlen,
      S15_AXI_awsize => S15_AXI_awsize,
      S15_AXI_awburst => S15_AXI_awburst,
      S15_AXI_awlock => S15_AXI_awlock,
      S15_AXI_awcache => S15_AXI_awcache,
      S15_AXI_awprot => S15_AXI_awprot,
      S15_AXI_awqos => S15_AXI_awqos,
      S15_AXI_awvalid => S15_AXI_awvalid,
      S15_AXI_awready => S15_AXI_awready,
      S15_AXI_wdata => S15_AXI_wdata,
      S15_AXI_wstrb => S15_AXI_wstrb,
      S15_AXI_wlast => S15_AXI_wlast,
      S15_AXI_wvalid => S15_AXI_wvalid,
      S15_AXI_wready => S15_AXI_wready,
      S15_AXI_bresp => S15_AXI_bresp,
      S15_AXI_bvalid => S15_AXI_bvalid,
      S15_AXI_bready => S15_AXI_bready,
      M00_AXI_awaddr => M00_AXI_awaddr,
      M00_AXI_awlen => M00_AXI_awlen,
      M00_AXI_awsize => M00_AXI_awsize,
      M00_AXI_awburst => M00_AXI_awburst,
      M00_AXI_awlock => M00_AXI_awlock,
      M00_AXI_awcache => M00_AXI_awcache,
      M00_AXI_awprot => M00_AXI_awprot,
      M00_AXI_awqos => M00_AXI_awqos,
      M00_AXI_awvalid => M00_AXI_awvalid,
      M00_AXI_awready => M00_AXI_awready,
      M00_AXI_wdata => M00_AXI_wdata,
      M00_AXI_wstrb => M00_AXI_wstrb,
      M00_AXI_wlast => M00_AXI_wlast,
      M00_AXI_wvalid => M00_AXI_wvalid,
      M00_AXI_wready => M00_AXI_wready,
      M00_AXI_bresp => M00_AXI_bresp,
      M00_AXI_bvalid => M00_AXI_bvalid,
      M00_AXI_bready => M00_AXI_bready,
      M00_AXI_araddr => M00_AXI_araddr,
      M00_AXI_arlen => M00_AXI_arlen,
      M00_AXI_arsize => M00_AXI_arsize,
      M00_AXI_arburst => M00_AXI_arburst,
      M00_AXI_arlock => M00_AXI_arlock,
      M00_AXI_arcache => M00_AXI_arcache,
      M00_AXI_arprot => M00_AXI_arprot,
      M00_AXI_arqos => M00_AXI_arqos,
      M00_AXI_arvalid => M00_AXI_arvalid,
      M00_AXI_arready => M00_AXI_arready,
      M00_AXI_rdata => M00_AXI_rdata,
      M00_AXI_rresp => M00_AXI_rresp,
      M00_AXI_rlast => M00_AXI_rlast,
      M00_AXI_rvalid => M00_AXI_rvalid,
      M00_AXI_rready => M00_AXI_rready
    );
END version1_stream_interconnect_0_arch;
