# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_xbar_1/version1_xbar_1.xci
# IP: The module: 'version1_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_xbar_1/version1_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'version1_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_xbar_1/version1_xbar_1.xci
# IP: The module: 'version1_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version1/ip/version1_xbar_1/version1_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'version1_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
