# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/version3_stream_interconnect_fft_0.xci
# IP: The module: 'version3_stream_interconnect_fft_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/bd_6c86.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_0/bd_6c86_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_1/bd_6c86_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_2/bd_6c86_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_3/bd_6c86_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_4/bd_6c86_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_5/bd_6c86_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_6/bd_6c86_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_7/bd_6c86_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_8/bd_6c86_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_9/bd_6c86_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_10/bd_6c86_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_11/bd_6c86_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_12/bd_6c86_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_13/bd_6c86_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_14/bd_6c86_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_15/bd_6c86_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_16/bd_6c86_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_17/bd_6c86_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_18/bd_6c86_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_19/bd_6c86_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_20/bd_6c86_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_21/bd_6c86_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_22/bd_6c86_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_23/bd_6c86_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_24/bd_6c86_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_25/bd_6c86_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_26/bd_6c86_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_27/bd_6c86_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_28/bd_6c86_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_29/bd_6c86_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_30/bd_6c86_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_31/bd_6c86_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_32/bd_6c86_s04mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_33/bd_6c86_s04tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_34/bd_6c86_s04sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_35/bd_6c86_s04a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_36/bd_6c86_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_37/bd_6c86_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_38/bd_6c86_s05mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_39/bd_6c86_s05tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_40/bd_6c86_s05sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_41/bd_6c86_s05a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_42/bd_6c86_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_43/bd_6c86_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_44/bd_6c86_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_45/bd_6c86_s06mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_46/bd_6c86_s06tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_47/bd_6c86_s06sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_48/bd_6c86_s06a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_49/bd_6c86_sarn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_50/bd_6c86_srn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_51/bd_6c86_s07mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_52/bd_6c86_s07tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_53/bd_6c86_s07sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_54/bd_6c86_s07a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_55/bd_6c86_sarn_5.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_56/bd_6c86_srn_5.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_57/bd_6c86_s08mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_58/bd_6c86_s08tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_59/bd_6c86_s08sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_60/bd_6c86_s08a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_61/bd_6c86_sawn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_62/bd_6c86_swn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_63/bd_6c86_sbn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_64/bd_6c86_s09mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_65/bd_6c86_s09tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_66/bd_6c86_s09sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_67/bd_6c86_s09a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_68/bd_6c86_sarn_6.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_69/bd_6c86_srn_6.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_70/bd_6c86_s10mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_71/bd_6c86_s10tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_72/bd_6c86_s10sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_73/bd_6c86_s10a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_74/bd_6c86_sarn_7.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_75/bd_6c86_srn_7.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_76/bd_6c86_s11mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_77/bd_6c86_s11tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_78/bd_6c86_s11sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_79/bd_6c86_s11a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_80/bd_6c86_sawn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_81/bd_6c86_swn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_82/bd_6c86_sbn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_83/bd_6c86_s12mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_84/bd_6c86_s12tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_85/bd_6c86_s12sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_86/bd_6c86_s12a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_87/bd_6c86_sarn_8.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_88/bd_6c86_srn_8.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_89/bd_6c86_sawn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_90/bd_6c86_swn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_91/bd_6c86_sbn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_92/bd_6c86_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_93/bd_6c86_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_94/bd_6c86_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_95/bd_6c86_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_96/bd_6c86_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_97/bd_6c86_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_98/bd_6c86_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_1/bd_6c86_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_1/bd_6c86_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_2/bd_6c86_arsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_3/bd_6c86_rsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_4/bd_6c86_awsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_5/bd_6c86_wsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_6/bd_6c86_bsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_10/bd_6c86_s00a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_11/bd_6c86_sarn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_12/bd_6c86_srn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_16/bd_6c86_s01a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_17/bd_6c86_sarn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_18/bd_6c86_srn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_22/bd_6c86_s02a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_23/bd_6c86_sawn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_24/bd_6c86_swn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_25/bd_6c86_sbn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_29/bd_6c86_s03a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_30/bd_6c86_sarn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_31/bd_6c86_srn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_35/bd_6c86_s04a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_36/bd_6c86_sarn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_37/bd_6c86_srn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_41/bd_6c86_s05a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_42/bd_6c86_sawn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_43/bd_6c86_swn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_44/bd_6c86_sbn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_48/bd_6c86_s06a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_49/bd_6c86_sarn_4_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_50/bd_6c86_srn_4_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_54/bd_6c86_s07a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_55/bd_6c86_sarn_5_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_56/bd_6c86_srn_5_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_60/bd_6c86_s08a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_61/bd_6c86_sawn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_62/bd_6c86_swn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_63/bd_6c86_sbn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_67/bd_6c86_s09a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_68/bd_6c86_sarn_6_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_69/bd_6c86_srn_6_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_73/bd_6c86_s10a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_74/bd_6c86_sarn_7_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_75/bd_6c86_srn_7_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_79/bd_6c86_s11a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_80/bd_6c86_sawn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_81/bd_6c86_swn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_82/bd_6c86_sbn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_86/bd_6c86_s12a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_87/bd_6c86_sarn_8_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_88/bd_6c86_srn_8_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_89/bd_6c86_sawn_4_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_90/bd_6c86_swn_4_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_91/bd_6c86_sbn_4_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_92/bd_6c86_m00s2a_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_93/bd_6c86_m00arn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_94/bd_6c86_m00rn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_95/bd_6c86_m00awn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_96/bd_6c86_m00wn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_97/bd_6c86_m00bn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'version3_stream_interconnect_fft_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/version3_stream_interconnect_fft_0.xci
# IP: The module: 'version3_stream_interconnect_fft_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/bd_6c86.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_0/bd_6c86_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_1/bd_6c86_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_2/bd_6c86_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_3/bd_6c86_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_4/bd_6c86_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_5/bd_6c86_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_6/bd_6c86_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_7/bd_6c86_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_8/bd_6c86_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_9/bd_6c86_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_10/bd_6c86_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_11/bd_6c86_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_12/bd_6c86_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_13/bd_6c86_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_14/bd_6c86_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_15/bd_6c86_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_16/bd_6c86_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_17/bd_6c86_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_18/bd_6c86_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_19/bd_6c86_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_20/bd_6c86_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_21/bd_6c86_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_22/bd_6c86_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_23/bd_6c86_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_24/bd_6c86_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_25/bd_6c86_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_26/bd_6c86_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_27/bd_6c86_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_28/bd_6c86_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_29/bd_6c86_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_30/bd_6c86_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_31/bd_6c86_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_32/bd_6c86_s04mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_33/bd_6c86_s04tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_34/bd_6c86_s04sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_35/bd_6c86_s04a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_36/bd_6c86_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_37/bd_6c86_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_38/bd_6c86_s05mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_39/bd_6c86_s05tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_40/bd_6c86_s05sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_41/bd_6c86_s05a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_42/bd_6c86_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_43/bd_6c86_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_44/bd_6c86_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_45/bd_6c86_s06mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_46/bd_6c86_s06tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_47/bd_6c86_s06sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_48/bd_6c86_s06a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_49/bd_6c86_sarn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_50/bd_6c86_srn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_51/bd_6c86_s07mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_52/bd_6c86_s07tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_53/bd_6c86_s07sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_54/bd_6c86_s07a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_55/bd_6c86_sarn_5.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_56/bd_6c86_srn_5.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_57/bd_6c86_s08mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_58/bd_6c86_s08tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_59/bd_6c86_s08sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_60/bd_6c86_s08a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_61/bd_6c86_sawn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_62/bd_6c86_swn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_63/bd_6c86_sbn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_64/bd_6c86_s09mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_65/bd_6c86_s09tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_66/bd_6c86_s09sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_67/bd_6c86_s09a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_68/bd_6c86_sarn_6.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_69/bd_6c86_srn_6.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_70/bd_6c86_s10mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_71/bd_6c86_s10tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_72/bd_6c86_s10sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_73/bd_6c86_s10a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_74/bd_6c86_sarn_7.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_75/bd_6c86_srn_7.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_76/bd_6c86_s11mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_77/bd_6c86_s11tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_78/bd_6c86_s11sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_79/bd_6c86_s11a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_80/bd_6c86_sawn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_81/bd_6c86_swn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_82/bd_6c86_sbn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_83/bd_6c86_s12mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_84/bd_6c86_s12tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_85/bd_6c86_s12sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_86/bd_6c86_s12a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_87/bd_6c86_sarn_8.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_88/bd_6c86_srn_8.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_89/bd_6c86_sawn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_90/bd_6c86_swn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_91/bd_6c86_sbn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_92/bd_6c86_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_93/bd_6c86_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_94/bd_6c86_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_95/bd_6c86_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_96/bd_6c86_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_97/bd_6c86_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_98/bd_6c86_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_1/bd_6c86_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_1/bd_6c86_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_2/bd_6c86_arsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_3/bd_6c86_rsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_4/bd_6c86_awsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_5/bd_6c86_wsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_6/bd_6c86_bsw_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_10/bd_6c86_s00a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_11/bd_6c86_sarn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_12/bd_6c86_srn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_16/bd_6c86_s01a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_17/bd_6c86_sarn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_18/bd_6c86_srn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_22/bd_6c86_s02a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_23/bd_6c86_sawn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_24/bd_6c86_swn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_25/bd_6c86_sbn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_29/bd_6c86_s03a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_30/bd_6c86_sarn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_31/bd_6c86_srn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_35/bd_6c86_s04a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_36/bd_6c86_sarn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_37/bd_6c86_srn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_41/bd_6c86_s05a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_42/bd_6c86_sawn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_43/bd_6c86_swn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_44/bd_6c86_sbn_1_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_48/bd_6c86_s06a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_49/bd_6c86_sarn_4_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_50/bd_6c86_srn_4_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_54/bd_6c86_s07a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_55/bd_6c86_sarn_5_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_56/bd_6c86_srn_5_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_60/bd_6c86_s08a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_61/bd_6c86_sawn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_62/bd_6c86_swn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_63/bd_6c86_sbn_2_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_67/bd_6c86_s09a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_68/bd_6c86_sarn_6_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_69/bd_6c86_srn_6_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_73/bd_6c86_s10a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_74/bd_6c86_sarn_7_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_75/bd_6c86_srn_7_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_79/bd_6c86_s11a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_80/bd_6c86_sawn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_81/bd_6c86_swn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_82/bd_6c86_sbn_3_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_86/bd_6c86_s12a2s_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_87/bd_6c86_sarn_8_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_88/bd_6c86_srn_8_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_89/bd_6c86_sawn_4_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_90/bd_6c86_swn_4_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_91/bd_6c86_sbn_4_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_92/bd_6c86_m00s2a_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_93/bd_6c86_m00arn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_94/bd_6c86_m00rn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_95/bd_6c86_m00awn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_96/bd_6c86_m00wn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/bd_0/ip/ip_97/bd_6c86_m00bn_0_ooc.xdc

# XDC: c:/Final_Year_Project/Architecture/BCI_SOC/vhdl/xilinxprj/BCI_SOC.srcs/sources_1/bd/version3/ip/version3_stream_interconnect_fft_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'version3_stream_interconnect_fft_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
